branches/myshop/src/com/faithbj/shop/entity/Member.java
package com.faithbj.shop.entity;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Transient;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;
import org.hibernate.annotations.CollectionOfElements;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;
import org.hibernate.annotations.MapKey;

import com.faithbj.custom.vegetable.entity.FieldBlock;
import com.faithbj.custom.vegetable.entity.FieldBlockCartItem;
import com.faithbj.custom.vegetable.entity.MemberAuth;
import com.faithbj.custom.vegetable.entity.RendBlock;

/**
 * 实体类 - 会员
 * <p>Copyright: Copyright (c) 2011</p> 
 * 
 * <p>Company: www.faithbj.com</p>
 * 
 * @author 	Barney Woo
 * @date 	2012-01-12
 * @version 1.0
 */

@Entity
public class Member extends BaseMember {

	//--------------------------------------------------------------------
	//vegetable member stuff
	//--------------------------------------------------------------------
	private List<RendBlock> rendBlockList = null;
	private List<MemberAuth> authList = null;
	
	private Set<FieldBlock> favoriteFieldBlockSet;// 收藏夹租赁块
	private Set<FieldBlockCartItem> fieldBlockCartItemSet;// 购物车项
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public List<RendBlock> getRendBlockList()
	{
		return rendBlockList;
	}
	public void setRendBlockList(List<RendBlock> rendBlockList)
	{
		this.rendBlockList = rendBlockList;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	public List<MemberAuth> getAuthList()
	{
		return authList;
	}
	public void setAuthList(List<MemberAuth> authList)
	{
		this.authList = authList;
	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	public Set<FieldBlock> getFavoriteFieldBlockSet()
	{
		return favoriteFieldBlockSet;
	}
	public void setFavoriteFieldBlockSet(Set<FieldBlock> favoriteFieldBlockSet)
	{
		this.favoriteFieldBlockSet = favoriteFieldBlockSet;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	@Cascade(value = { CascadeType.DELETE })
	@OrderBy("createDate desc")
	public Set<FieldBlockCartItem> getFieldBlockCartItemSet()
	{
		return fieldBlockCartItemSet;
	}
	public void setFieldBlockCartItemSet(
			Set<FieldBlockCartItem> fieldBlockCartItemSet)
	{
		this.fieldBlockCartItemSet = fieldBlockCartItemSet;
	}
	
	//--------------------------------------------------------------------
	//original code, don't modify
	//--------------------------------------------------------------------
	private static final long serialVersionUID = -5222673112266471971L;

	@Column(updatable = false, nullable = false, unique = true)
	public String getUsername() {
		return super.getUsername();
	}

	@Column(nullable = false)
	public String getPassword() {
		return super.getPassword();
	}
	
	@Column(nullable = false)
	public String getEmail() {
		return super.getEmail();
	}
	
	@Column(nullable = false)
	public Integer getPoint() {
		return super.getPoint();
	}


	@Column(precision = 15, scale = 5, nullable = false)
	public BigDecimal getDeposit() {
		return super.getDeposit();
	}

	@Column(nullable = false)
	public Boolean getIsAccountEnabled() {
		return super.getIsAccountEnabled();
	}

	@Column(nullable = false)
	public Boolean getIsAccountLocked() {
		return super.getIsAccountLocked();
	}

	@Column(nullable = false)
	public Integer getLoginFailureCount() {
		return super.getLoginFailureCount();
	}
	
	@Column(nullable = false, updatable = false)
	public String getRegisterIp() {
		return super.getRegisterIp();
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(nullable = false)
	public MemberRank getMemberRank() {
		return super.getMemberRank();
	}
	
	@CollectionOfElements
	@MapKey(targetElement = MemberAttribute.class)
	@LazyCollection(LazyCollectionOption.TRUE)
	@Cascade(value = { CascadeType.DELETE })
	public Map<MemberAttribute, String> getMemberAttributeMapStore() {
		return super.getMemberAttributeMapStore();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	@Cascade(value = { CascadeType.DELETE })
	@OrderBy("createDate desc")
	public Set<Receiver> getReceiverSet() {
		return super.getReceiverSet();
	}
	
	@ManyToMany(fetch = FetchType.LAZY)
	@OrderBy("name desc")
	public Set<Product> getFavoriteProductSet() {
		return super.getFavoriteProductSet();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	@Cascade(value = { CascadeType.DELETE })
	@OrderBy("createDate desc")
	public Set<CartItem> getCartItemSet() {
		return super.getCartItemSet();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toMember")
	@Cascade(value = { CascadeType.DELETE })
	@OrderBy("createDate desc")
	public Set<Message> getInboxMessageSet() {
		return super.getInboxMessageSet();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fromMember")
	@Cascade(value = { CascadeType.DELETE })
	@OrderBy("createDate desc")
	public Set<Message> getOutboxMessageSet() {
		return super.getOutboxMessageSet();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	@OrderBy("createDate desc")
	public Set<Order> getOrderSet() {
		return super.getOrderSet();
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "member")
	@Cascade(value = { CascadeType.DELETE })
	@OrderBy("createDate desc")
	public Set<Deposit> getDepositSet() {
		return super.getDepositSet();
	}

	@SuppressWarnings("unchecked")
	@Transient
	public Map<MemberAttribute, List<String>> getMemberAttributeMap() {
		return super.getMemberAttributeMap();
	}

	@Transient
	public void setMemberAttributeMap(Map<MemberAttribute, List<String>> memberAttributeMap) {
		super.setMemberAttributeMap(memberAttributeMap);
	}
	

}

branches/myshop/src/com/faithbj/custom/vegetable/action/fieldmember/FieldBlockAction.java
package com.faithbj.custom.vegetable.action.fieldmember;

import javax.annotation.Resource;

import org.apache.struts2.convention.annotation.ParentPackage;

import com.faithbj.custom.vegetable.entity.FieldBlock;
import com.faithbj.custom.vegetable.service.FieldBlockService;
import com.faithbj.shop.action.shop.BaseShopAction;

/**
 * 前台Action类 - 可租赁土地块
 * <p>Copyright: Copyright (c) 2012</p> 
 * 
 * <p>Company: www.faithbj.com</p>
 * 
 * @author 	barney
 * @date 	2012-01-28
 * @version 1.0
 */

@ParentPackage("member")
public class FieldBlockAction extends BaseShopAction
{
	private static final long serialVersionUID = 1L;
	
	private String viewType = null;
	
	private FieldBlock fieldBlock = null;

	@Resource
	private FieldBlockService fieldBlockService;
	
	public String list() {
		pager = this.fieldBlockService.findByPager(pager);
		return LIST;
	}

	public String content()
	{
		this.fieldBlock = this.fieldBlockService.load(this.id);
		return "content";
	}

	public String getViewType()
	{
		return viewType;
	}
	public void setViewType(String viewType)
	{
		this.viewType = viewType;
	}

	public FieldBlock getFieldBlock()
	{
		return fieldBlock;
	}

	public void setFieldBlock(FieldBlock fieldBlock)
	{
		this.fieldBlock = fieldBlock;
	}
}

branches/myshop/src/com/faithbj/custom/vegetable/action/fieldmember/FieldBlockCartItemAction.java
package com.faithbj.custom.vegetable.action.fieldmember;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

import javax.annotation.Resource;

import org.apache.commons.lang.StringUtils;
import org.apache.struts2.convention.annotation.ParentPackage;

import com.faithbj.custom.vegetable.entity.FieldBlock;
import com.faithbj.custom.vegetable.entity.FieldBlockCartItem;
import com.faithbj.custom.vegetable.entity.MemberAuth;
import com.faithbj.custom.vegetable.service.FieldBlockCartItemService;
import com.faithbj.custom.vegetable.service.FieldBlockService;
import com.faithbj.shop.action.shop.BaseShopAction;
import com.faithbj.shop.bean.SystemConfig.PointType;
import com.faithbj.shop.entity.CartItem;
import com.faithbj.shop.entity.Member;
import com.faithbj.shop.util.SystemConfigUtil;
import com.opensymphony.xwork2.interceptor.annotations.InputConfig;
import com.opensymphony.xwork2.validator.annotations.RequiredStringValidator;
import com.opensymphony.xwork2.validator.annotations.Validations;

@ParentPackage("shop")
public class FieldBlockCartItemAction extends BaseShopAction
{
	private static final long serialVersionUID = -1011629481509715547L;
	
	private Integer quantity;
	private List<FieldBlockCartItem> fieldBlockCartItemList = new ArrayList<FieldBlockCartItem>();

	private Integer totalQuantity;// 商品总数
	private Integer totalPoint;// 总积分
	private BigDecimal totalPrice;// 总计商品价格
	
	private String isTrusteeFeeEnabled = null;
	private String isDeliveryFeeEnabled = null;
	
	@Resource
	private FieldBlockService fieldBlockService;
	
	@Resource
	private FieldBlockCartItemService fieldBlockCartItemService = null;
	
	// 添加购物车项
	@Validations(
		requiredStrings = {
			@RequiredStringValidator(fieldName = "id", message = "ID不允许为空!")
		}
	)
	@InputConfig(resultName = "error")
	public String ajaxAdd() {
		Member member = this.getLoginMember();
		List<MemberAuth> authList = member.getAuthList();
		boolean isAuth = false;
		for(MemberAuth auth : authList){
			if(auth.getType().equals("0")){
				isAuth = true;
				break;
			}
		}
		if(!isAuth){
			return ajaxJsonErrorMessage("您没有承包土地的权限！");
		}
		FieldBlock fieldBlock = fieldBlockService.load(id);
		if (!fieldBlock.getIsMarketable()) {
			return ajaxJsonErrorMessage("此商品已下架!");
		}
		if (quantity == null || quantity < 1) {
			quantity = 1;
		}
		Integer totalQuantity = 0;// 总计商品数量
		BigDecimal totalPrice = new BigDecimal("0");// 总计商品价格
		Member loginMember = getLoginMember();
		if (loginMember == null) {
			return ajaxJsonErrorMessage("请先登录");
		} else {
			boolean isExist = false;
			Set<FieldBlockCartItem> previousFieldBlockCartItemList = loginMember.getFieldBlockCartItemSet();
			if (previousFieldBlockCartItemList != null) {
				for (FieldBlockCartItem previousCartItem : previousFieldBlockCartItemList) {
					if (StringUtils.equals(previousCartItem.getFieldBlock().getId(), id)) {
						isExist = true;
						previousCartItem.setQuantity(previousCartItem.getQuantity() + quantity);
						if (fieldBlock.getStore() != null && previousCartItem.getQuantity() > fieldBlock.getStore()) {
							return ajaxJsonErrorMessage("添加购物车失败，商品库存不足!");
						}
						this.fieldBlockCartItemService.update(previousCartItem);
					}
					totalQuantity += previousCartItem.getQuantity();
					totalPrice =  previousCartItem.getPreferentialPrice().multiply(new BigDecimal(previousCartItem.getQuantity().toString())).add(totalPrice);
				}
			}
			Set<CartItem> previousCartItemList = loginMember.getCartItemSet();
			if (previousCartItemList.size()!=0) {
				for (CartItem previousCartItem : previousCartItemList) {
					
					totalQuantity += previousCartItem.getQuantity();
					totalPrice =  previousCartItem.getPreferentialPrice().multiply(new BigDecimal(previousCartItem.getQuantity().toString())).add(totalPrice);
				}
			}
			if (!isExist) {
				FieldBlockCartItem cartItem = new FieldBlockCartItem();
				cartItem.setMember(loginMember);
				cartItem.setFieldBlock(fieldBlock);
				cartItem.setQuantity(quantity);
				cartItem.setIsTrusteeFeeEnabled("true".equals(isTrusteeFeeEnabled));
				cartItem.setIsDeliveryFeeEnabled("true".equals(isDeliveryFeeEnabled));
				if (fieldBlock.getStore() != null && cartItem.getQuantity() > fieldBlock.getStore()) {
					return ajaxJsonErrorMessage("添加购物车失败，商品库存不足!");
				}
				this.fieldBlockCartItemService.save(cartItem);
				totalQuantity += quantity;
				totalPrice =  cartItem.getPreferentialPrice().multiply(new BigDecimal(quantity.toString())).add(totalPrice);
			}
		}
		totalPrice = SystemConfigUtil.getOrderScaleBigDecimal(totalPrice);
		DecimalFormat decimalFormat = new DecimalFormat(getOrderUnitCurrencyFormat());
		String totalPriceString = decimalFormat.format(totalPrice);
		Map<String, String> jsonMap = new HashMap<String, String>();
		jsonMap.put(STATUS, SUCCESS);
		jsonMap.put(MESSAGE, "添加至购物车成功！");
		jsonMap.put("totalQuantity", totalQuantity.toString());
		jsonMap.put("totalPrice", totalPriceString);
		return ajaxJson(jsonMap);
	}
	
//	// 修改购物车项
//	@InputConfig(resultName = "error")
//	public String ajaxEdit() {
//		if (quantity == null || quantity < 1) {
//			quantity = 1;
//		}
//		Member loginMember = getLoginMember();
//		totalQuantity = 0;
//		totalPoint = 0;
//		totalPrice = new BigDecimal("0");
//		BigDecimal subtotalPrice = new BigDecimal("0");
//		if (loginMember == null) {
//			return ajaxJsonErrorMessage("请先登录");
//		} else {
//			Set<FieldBlockCartItem> fieldBlockCartItemSet = loginMember.getFieldBlockCartItemSet();
//			if (fieldBlockCartItemSet != null) {
//				for (FieldBlockCartItem cartItem : fieldBlockCartItemSet) {
//					FieldBlock fieldBlock = cartItem.getFieldBlock();
//					if (StringUtils.equals(id, cartItem.getFieldBlock().getId())) {
//						cartItem.setQuantity(quantity);
//						if (fieldBlock.getStore() != null && cartItem.getQuantity() > fieldBlock.getStore()) {
//							return ajaxJsonErrorMessage("商品库存不足！");
//						}
//						fieldBlockCartItemService.update(cartItem);
//						subtotalPrice = cartItem.getSubtotalPrice();
//					}
//					totalQuantity += cartItem.getQuantity();
//					if (getSystemConfig().getPointType() == PointType.productSet) {
//						totalPoint = fieldBlock.getPoint() * cartItem.getQuantity() + totalPoint;
//					}
//					totalPrice = cartItem.getPreferentialPrice().multiply(new BigDecimal(cartItem.getQuantity().toString())).add(totalPrice);
//				}
//			}
//		}
//		DecimalFormat orderUnitCurrencyFormat = new DecimalFormat(getOrderUnitCurrencyFormat());
//		DecimalFormat orderCurrencyFormat = new DecimalFormat(getOrderCurrencyFormat());
//		totalPrice = SystemConfigUtil.getOrderScaleBigDecimal(totalPrice);
//		if (getSystemConfig().getPointType() == PointType.orderAmount) {
//			totalPoint = totalPrice.divide(new BigDecimal(getSystemConfig().getPointScale().toString())).setScale(0, RoundingMode.DOWN).intValue();
//		}
//		String subtotalPriceString = orderCurrencyFormat.format(subtotalPrice);
//		String totalPriceString = orderUnitCurrencyFormat.format(totalPrice);
//		Map<String, String> jsonMap = new HashMap<String, String>();
//		jsonMap.put("subtotalPrice", subtotalPriceString);
//		jsonMap.put("totalQuantity", totalQuantity.toString());
//		jsonMap.put("totalPoint", totalPoint.toString());
//		jsonMap.put("totalPrice", totalPriceString);
//		jsonMap.put(STATUS, SUCCESS);
//		return ajaxJson(jsonMap);
//	}
//	
//	// 删除购物车项
//	@InputConfig(resultName = "error")
//	@SuppressWarnings("unchecked")
//	public String ajaxDelete() {
//		Member loginMember = getLoginMember();
//		totalQuantity = 0;
//		totalPoint = 0;
//		totalPrice = new BigDecimal("0");
//		if (loginMember == null) {
//			return ajaxJsonErrorMessage("请先登录");
//		} else {
//			Set<FieldBlockCartItem> cartItemSet = loginMember.getFieldBlockCartItemSet();
//			if (cartItemSet != null) {
//				for (FieldBlockCartItem cartItem : cartItemSet) {
//					if (StringUtils.equals(cartItem.getFieldBlock().getId(), id)) {
//						fieldBlockCartItemService.delete(cartItem);
//					} else {
//						FieldBlock fieldBlock = cartItem.getFieldBlock();
//						totalQuantity += cartItem.getQuantity();
//						if (getSystemConfig().getPointType() == PointType.productSet) {
//							totalPoint = fieldBlock.getPoint() * cartItem.getQuantity() + totalPoint;
//						}
//						totalPrice = cartItem.getPreferentialPrice().multiply(new BigDecimal(cartItem.getQuantity().toString())).add(totalPrice);
//					}
//				}
//			}
//		}
//		totalPrice = SystemConfigUtil.getOrderScaleBigDecimal(totalPrice);
//		if (getSystemConfig().getPointType() == PointType.orderAmount) {
//			totalPoint = totalPrice.divide(new BigDecimal(getSystemConfig().getPointScale().toString())).setScale(0, RoundingMode.DOWN).intValue();
//		}
//		DecimalFormat decimalFormat = new DecimalFormat(getOrderUnitCurrencyFormat());
//		String totalPriceString = decimalFormat.format(totalPrice);
//		Map<String, String> jsonMap = new HashMap<String, String>();
//		jsonMap.put("totalQuantity", totalQuantity.toString());
//		jsonMap.put("totalPoint", totalPoint.toString());
//		jsonMap.put("totalPrice", totalPriceString);
//		jsonMap.put(STATUS, SUCCESS);
//		jsonMap.put(MESSAGE, "商品删除成功！");
//		return ajaxJson(jsonMap);
//	}
	
	public Integer getQuantity()
	{
		return quantity;
	}
	public void setQuantity(Integer quantity)
	{
		this.quantity = quantity;
	}
	public List<FieldBlockCartItem> getFieldBlockCartItemList()
	{
		return fieldBlockCartItemList;
	}
	public void setFieldBlockCartItemList(List<FieldBlockCartItem> fieldBlockCartItemList)
	{
		this.fieldBlockCartItemList = fieldBlockCartItemList;
	}

branches/myshop/WebRoot/WEB-INF/template/fieldmember/field_favorite_list.ftl
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>承包土地收藏 - Powered By ${systemConfig.systemName}</title>
<meta name="Author" content="MyShop Team" />
<meta name="Copyright" content="MyShop" />
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<#include "/WEB-INF/template/common/include.ftl">
<link href="${base}/template/shop/css/login.css" rel="stylesheet" type="text/css" />
<link href="${base}/template/shop/css/register.css" rel="stylesheet" type="text/css" />
<link href="${base}/template/shop/css/member_center.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="${base}/template/shop/js/login.js"></script>
<script type="text/javascript" src="${base}/template/shop/js/register.js"></script>
<script type="text/javascript">
$().ready( function() {
	
	// 删除
	$(".deleteFavorite").click( function() {
		if (confirm("您确定要删除吗？") == false) {
			return false;
		}
	});
	
});
</script>
</head>
<body class="memberCenter">
	<#include "/WEB-INF/template/shop/header.ftl">
	<div class="body favoriteList">
		<#include "/WEB-INF/template/fieldmember/include/field_center_menu.ftl">
		<div class="bodyRight">
			<div class="memberCenterDetail">
				<div class="top">
					承包土地收藏
				</div>
				<div class="middle">
					<div class="blank"></div>
					<table class="listTable">
						<tr>
							<th>承包土地图片</th>
							<th>承包土地名称</th>
							<th>承包土地价格</th>
							<th>操作</th>
						</tr>
						<#list pager.list as list>
							<tr>
								<td>
									<a href="${base}/fieldmember/field_block!content.action?id=${list.id}" class="productImage" target="_blank">
										<img src="${base}${(list.productImageList[0].thumbnailProductImagePath)!systemConfig.defaultThumbnailProductImagePath}" alt="${list.name}" />
									</a>
								</td>
								<td>
									<a href="${base}/fieldmember/field_block!content.action?id=${list.id}" target="_blank">${list.name}</a>
								</td>
								<td>${list.rent}</td>
								<td>
									<a href="${base}/fieldmember/field_favorite!delete.action?id=${list.id}" class="deleteFavorite">删除</a>
								</td>
							</tr>
						</#list>
					</table>
					<div class="blank"></div>
         			<link href="${base}/template/shop/css/pager.css" rel="stylesheet" type="text/css" />
         			<#import "/WEB-INF/template/shop/pager.ftl" as p>
         			<@p.pager pager = pager baseUrl = "/shop/favorite!list.action" />
				</div>
				<div class="bottom"></div>
			</div>
		</div>
		<div class="blank"></div>
		<#include "/WEB-INF/template/shop/friend_link.ftl">
	</div>
	<div class="blank"></div>
	<#include "/WEB-INF/template/shop/footer.ftl">
</body>
</html>

branches/myshop/WebRoot/WEB-INF/template/fieldmember/field_manage_index.ftl
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>土地会员中心 - Powered By ${systemConfig.systemName}</title>
<meta name="Author" content="MyShop Team" />
<meta name="Copyright" content="MyShop" />
<link rel="icon" href="favicon.ico" type="image/x-icon" />
<#include "/WEB-INF/template/common/include.ftl">
<link href="${base}/template/shop/css/login.css" rel="stylesheet" type="text/css" />
<link href="${base}/template/shop/css/register.css" rel="stylesheet" type="text/css" />
<link href="${base}/template/shop/css/member_center.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="${base}/template/shop/js/login.js"></script>
<script type="text/javascript" src="${base}/template/shop/js/register.js"></script>
</head>
<body class="memberCenter">
	<#include "/WEB-INF/template/shop/header.ftl">
	<div class="body memberCenterIndex">
		<#include "/WEB-INF/template/fieldmember/include/field_center_menu.ftl">
		<div class="bodyRight">
			<div class="memberCenterDetail">
				<div class="top">
					<strong>${loginMember.username}的自留地
				</div>
				<div class="middle">
					<div class="blank"></div>
					<table class="listTable">
						<tr>
							<td colspan="4">
								您目前是[${loginMember.memberRank.name}]
								<#if loginMember.memberRank.preferentialScale != 100>
									<span class="red">[优惠百分比：${loginMember.memberRank.preferentialScale}%]</span>
								</#if>
							</td>
						</tr>
						<tr>
							<th>我的承包地块总数量</th>
							<td>
								${rendBlockSize}&nbsp;&nbsp;
								<a href="order!list.action">[查看我的承包地块]</a>
							</td>
						</tr>
						<tr>
							<th>[空闲]耕种地块</th>
							<td>
								${freeSize}&nbsp;&nbsp;
								<a href="my_farming_block!list.action?farmingBlockStatus=0">[查看空闲耕种地块]</a>
							</td>
							<th>[播种]耕种地块</th>
							<td>
								${seedingSize}&nbsp;&nbsp;
								<a href="my_farming_block!list.action?farmingBlockStatus=2">[查看播种耕种地块]</a>
							</td>
						</tr>
						<tr>
							<th>[生长]耕种地块</th>
							<td>
								${growingSize}&nbsp;&nbsp;
								<a href="my_farming_block!list.action?farmingBlockStatus=4">[查看生长耕种地块]</a>
							</td>
							<th>[收获]耕种地块</th>
							<td>
								${harvestSize}&nbsp;&nbsp;
								<a href="my_farming_block!list.action?farmingBlockStatus=6">[查看收获耕种地块]</a>
							</td>
						</tr>
						<tr>
							<th>[清理]耕种地块</th>
							<td>
								${cleanSize}&nbsp;&nbsp;
								<a href="my_farming_block!list.action?farmingBlockStatus=8">[查看清理耕种地块]</a>
							</td>
						</tr>
					</table>
					
					<table class="listTable" style='margin-top:5px;'>
						<tr>
							<th>我的收获记录</th>
							<td>
								${rendBlockSize}&nbsp;&nbsp;
								<a href="my_harvest_record!list.action">[查看我的收获记录]</a>
							</td>
						</tr>
					</table>
					
					<table class="listTable" style='margin-top:5px;'>
						<tr>
							<th>我的承包地块收藏</th>
							<td>
								${favoriteSize}&nbsp;&nbsp;
								<a href="field_favorite!list.action">[查看我的承包地块收藏]</a>
							</td>
						</tr>
					</table>
					
					<table class="listTable" style='margin-top:5px;'>
						<tr>
							<th>我的购物车中的承包地块</th>
							<td>
								${fieldBlockCartItemSize}&nbsp;&nbsp;
								<a href="field_favorite!list.action">[查看购物车中承包地块]</a>
							</td>
						</tr>
					</table>
					
					<div class="blank"></div>
				</div>
				<div class="bottom"></div>
			</div>
		</div>
		<div class="blank"></div>
		<#include "/WEB-INF/template/shop/friend_link.ftl">
	</div>
	<div class="blank"></div>
	<#include "/WEB-INF/template/shop/footer.ftl">
</body>
</html>